name: Tests

on:
  push:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    container: henriheimann/cpputest-cmake:v4.0
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build
        run: mkdir testing/build && cd testing/build && cmake .. && make

      - name: Test
        run: ./testing/build/run-all-tests
