name: test

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: henriheimann/cpputest-cmake:v4.0
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build
        run: mkdir test/build && cd test/build && cmake .. && make

      - name: Test
        run: ./test/build/run_all_tests
